image:
  repository: ghcr.io/yourorg/patient
  tag: v0.1.0

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: api.dev.digihealth.example
  path: /patients
  annotations: {}

env:
  - name: ASPNETCORE_URLS
    value: http://+:80
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector.otel:4317

volumeMounts:
  - name: secrets-store
    mountPath: /mnt/secrets
    readOnly: true

volumes:
  - name: secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: kv-digihealth-patient

resources:
  requests: { cpu: 200m, memory: 256Mi }
  limits:   { cpu: 500m, memory: 512Mi }
