apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interop
  annotations:
    kubernetes.io/ingress.class: nginx
{{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: interop
                port:
                  number: {{ .Values.service.port }}
